name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      id: version
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login"
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        echo "Fin de login"

    - name: Build docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t nic22/docker-graphql:$NEW_VERSION .

    - name: Push docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push nic22/docker-graphql:$NEW_VERSION
